# Generated by Django 5.1.1 on 2024-09-19 02:05

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "published": "A post visible to all",
        "draft": "A post visible only to the author",
        "archived": "An older post, for logged in users"
    }
    Status = apps.get_model("posts", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]